<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yashodhar-Lenovo-ideapad-300-15ISK" name="UnitTest" tests="1" failures="0" timestamp="11 Dec 2017 20:00:25 GMT" time="0.013" errors="1">
  <testcase name="testSalutationMessage" time="0.013" classname="UnitTest">
    <error type="java.lang.AssertionError" message="expected [dfasfas] but found [Hi!Manisha]">
      <![CDATA[java.lang.AssertionError: expected [dfasfas] but found [Hi!Manisha]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at UnitTest.testSalutationMessage(UnitTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.scalatest.testng.TestNGSuiteLike.run(TestNGSuiteLike.scala:261)
	at org.scalatest.testng.TestNGSuiteLike.run$(TestNGSuiteLike.scala:254)
	at org.scalatest.testng.TestNGSuite.run(TestNGSuite.scala:67)
	at org.scalatest.testng.TestNGSuiteLike.runTestNG(TestNGSuiteLike.scala:248)
	at org.scalatest.testng.TestNGSuiteLike.runTestNG$(TestNGSuiteLike.scala:227)
	at org.scalatest.testng.TestNGSuite.runTestNG(TestNGSuite.scala:67)
	at org.scalatest.testng.TestNGSuiteLike.run(TestNGSuiteLike.scala:149)
	at org.scalatest.testng.TestNGSuiteLike.run$(TestNGSuiteLike.scala:146)
	at org.scalatest.testng.TestNGSuite.run(TestNGSuite.scala:67)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testSalutationMessage -->
</testsuite> <!-- UnitTest -->
